# Generated by Django 2.2.4 on 2019-09-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190901_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_change_author', 'Can change author'),)},
        ),
    ]
